#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

assert_contains() {
  local pattern="$1"
  local file="$2"
  if ! grep -q "$pattern" "$ROOT/$file"; then
    fail "Expected '$pattern' in $file"
  fi
}

assert_absent() {
  local pattern="$1"
  shift
  local matches
  matches="$(grep -R -n "$pattern" "$@" 2>/dev/null || true)"
  if [[ -n "$matches" ]]; then
    printf '%s\n' "$matches" >&2
    fail "Unexpected stale docs or naming pattern"
  fi
}

DOC_FILES=(
  "$ROOT/README.md"
  "$ROOT/SKILL.md"
  "$ROOT/skills/graymatter"
  "$ROOT/plugins/graymatter/skills"
  "$ROOT/mcp-server/README.md"
  "$ROOT/docs"
  "$ROOT/plugins/graymatter/docs"
  "$ROOT/scripts"
  "$ROOT/tests/gm_light_bootstrap_test.sh"
  "$ROOT/tests/gm_light_up_test.sh"
)

future_sample="future local runnable sample"
future_service="provide a runnable GrayMatter Light local service"
raw_api_signup="api-0.valkyrlabs.com/v1/auth/signup"
generic_buy_credits="valkyrlabs.com/buy-credits"
generic_white_paper="valkyrlabs.com/funnel/white-paper"

assert_absent "$future_sample" "${DOC_FILES[@]}"
assert_absent "$future_service" "${DOC_FILES[@]}"
assert_absent "$raw_api_signup" "${DOC_FILES[@]}"
assert_absent "$generic_buy_credits" "${DOC_FILES[@]}"
assert_absent "$generic_white_paper" "${DOC_FILES[@]}"

assert_contains "gm-light-json-smoke" "README.md"
assert_contains "gm-light-json-smoke" "docs/graymatter-light.md"
assert_contains "gm-light-json-smoke" "plugins/graymatter/docs/graymatter-light.md"
assert_contains "gm-light-json-smoke" "scripts/package-graymatter"
assert_contains "gm-light-smoke" "README.md"
assert_contains "gm-light-smoke" "docs/graymatter-light.md"
assert_contains "gm-light-smoke" "plugins/graymatter/docs/graymatter-light.md"
assert_contains "gm-light-smoke" "scripts/package-graymatter"
assert_contains "gm-client" "README.md"
assert_contains "gm-record" "README.md"
assert_contains "gm-client" "SKILL.md"
assert_contains "gm-record" "SKILL.md"
assert_contains "package-graymatter" "SKILL.md"
assert_contains "gm-client" "skills/graymatter/SKILL.md"
assert_contains "gm-record" "skills/graymatter/SKILL.md"
assert_contains "package-graymatter" "skills/graymatter/SKILL.md"
assert_contains "gm-activation-fastlane" "skills/graymatter/SKILL.md"
assert_contains "gm-read" "skills/graymatter/SKILL.md"
assert_contains "gm-client" "plugins/graymatter/README.md"
assert_contains "gm-record" "plugins/graymatter/README.md"
assert_contains "gm-client" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "gm-record" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "package-graymatter" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "gm-activation-fastlane" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "gm-read" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "gm-client" "scripts/package-graymatter"
assert_contains "gm-record" "scripts/package-graymatter"
assert_contains "gm-client" "plugins/graymatter/scripts/package-graymatter"
assert_contains "gm-record" "plugins/graymatter/scripts/package-graymatter"
assert_contains "skills/graymatter-analytics/references/semantic-layer-template.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "scripts/package-graymatter" "scripts/package-graymatter"
assert_contains "scripts/package_graymatter.sh" "scripts/package-graymatter"
assert_contains "scripts/package-graymatter" "plugins/graymatter/scripts/package-graymatter"
assert_contains "scripts/package_graymatter.sh" "plugins/graymatter/scripts/package-graymatter"
assert_contains "docs/agent-discovery.md" "scripts/package-graymatter"
assert_contains "docs/awesome-codex-plugins.md" "scripts/package-graymatter"
assert_contains "docs/graymatter-light.md" "scripts/package-graymatter"
assert_contains "docs/openai-app-directory-submission.md" "scripts/package-graymatter"
assert_contains "docs/privacy-policy.md" "scripts/package-graymatter"
assert_contains "docs/reviewer-test-credentials.md" "scripts/package-graymatter"
assert_contains "docs/thorapi-integration.md" "scripts/package-graymatter"
assert_contains "openai-app/submission-manifest.json" "scripts/package-graymatter"
assert_contains "clawhub.json" "scripts/package-graymatter"
assert_contains "examples/memoryentry-basic.json" "scripts/package-graymatter"
assert_contains "examples/graymatter-light-memoryentry.yaml" "scripts/package-graymatter"
assert_contains "docs/agent-discovery.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "docs/awesome-codex-plugins.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "docs/graymatter-light.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "docs/openai-app-directory-submission.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "docs/privacy-policy.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "docs/reviewer-test-credentials.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "docs/thorapi-integration.md" "plugins/graymatter/scripts/package-graymatter"
assert_contains "openai-app/submission-manifest.json" "plugins/graymatter/scripts/package-graymatter"
assert_contains "clawhub.json" "plugins/graymatter/scripts/package-graymatter"
assert_contains "THORAPI_TEMPLATE=/app/api.hbs.yaml" "README.md"
assert_contains "THORAPI_SPEC=/app/api.yaml" "README.md"
assert_contains "THORAPI_TEMPLATE=/app/api.hbs.yaml" "docs/graymatter-light.md"
assert_contains "THORAPI_SPEC=/app/api.yaml" "docs/graymatter-light.md"
assert_contains "/v1/swarm-ops/graph" "docs/graymatter-light.md"
assert_contains "/v1/swarm-ops/graph" "plugins/graymatter/docs/graymatter-light.md"
assert_contains "/v1/swarm-ops/graph" "docs/thorapi-integration.md"
assert_contains "/v1/swarm-ops/graph" "plugins/graymatter/docs/thorapi-integration.md"
assert_contains "POST /v1/MemoryEntry/write" "docs/thorapi-integration.md"
assert_contains "POST /v1/MemoryEntry/write" "plugins/graymatter/docs/thorapi-integration.md"
assert_contains "GET /v1/api-docs" "docs/thorapi-integration.md"
assert_contains "GET /v1/api-docs" "plugins/graymatter/docs/thorapi-integration.md"
assert_contains "api.hbs.yaml template" "README.md"
assert_contains "rendered api.yaml" "README.md"
assert_contains "GrayMatter Light" "mcp-server/README.md"
assert_contains "VALKYR_API_BASE=http://localhost:8080/v1" "mcp-server/README.md"
assert_contains "gm-activation-fastlane" "README.md"
assert_contains "gm-activation-fastlane" "SKILL.md"
assert_contains "gm-activation-fastlane" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "gm-activation-fastlane" "scripts/package-graymatter"
assert_contains "Mandatory invariant preflight" "SKILL.md"
assert_contains "Mandatory invariant preflight" "skills/graymatter/SKILL.md"
assert_contains "Mandatory invariant preflight" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "Normalized object writes" "SKILL.md"
assert_contains "Normalized object writes" "skills/graymatter/SKILL.md"
assert_contains "Normalized object writes" "plugins/graymatter/skills/graymatter/SKILL.md"
assert_contains "gm-invariant-preflight" "README.md"
assert_contains "gm-invariant-preflight" "plugins/graymatter/README.md"
assert_contains "gm-invariant-preflight" "scripts/package-graymatter"
assert_contains "gm-invariant-preflight" "plugins/graymatter/scripts/package-graymatter"
assert_contains "graymatter_invariant_preflight" "mcp-server/README.md"
assert_contains "graymatter_invariant_preflight" "plugins/graymatter/mcp-server/README.md"
assert_contains "Raw bearer-token setup remains a debug/advanced path" "README.md"
assert_contains "retrieval receipts" "docs/agent-discovery.md"
assert_contains "retrieval receipts" "plugins/graymatter/docs/agent-discovery.md"
assert_contains "awesome-codex-plugins" "docs/awesome-codex-plugins.md"
assert_contains "awesome-codex-plugins" "plugins/graymatter/docs/awesome-codex-plugins.md"
assert_contains "TrustFabric" "README.md"
assert_contains "TrustFabric" "plugins/graymatter/README.md"
assert_contains "TrustFabric" "skills/graymatter/SKILL.md"
assert_contains "TrustFabric" "plugins/graymatter/skills/graymatter/SKILL.md"

echo "docs_consistency_test: ok"
